# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "robot"
BBFILE_PATTERN_robot = "^${LAYERDIR}/"
BBFILE_PRIORITY_robot = "6"

LAYERVERSION_robot = "1"
LAYERDEPENDS_robot = "core"
LAYERSERIES_COMPAT_robot = "scarthgap"
